experiment: "log_sim2exp_augmented-all"
config_path: "configs/pysr_linear_models_augmented_config.yml"

data_path: "data/merged_dfs_augmented_exp.csv"
input_col: "Ms (ampere/meter)_s"
target_col: "Ms (ampere/meter)_e_all_w_mock"
emb_col: None
sim_col: "Ms (ampere/meter)_s"
exp_col: "Ms (ampere/meter)_e_all_w_mock"
transform: 'log'

modeltypes: "pysr_linear"
threshold: 50000.
transform: 'log'
augmented: True

artifact_paths:
  root: "artifacts/"
  images: "artifacts/images/"
  models: "artifacts/models/"