experiment: "log_sim2exp_augmented-all"
config_path: "configs/pysr_linear_models_augmented_config_all.yml"
material_group: "all"
data_path: "data/merged_dfs_augmented_exp.csv"
input_col: "Ms (ampere/meter)_s"
target_col: "Ms (ampere/meter)_e_all_augmented"
emb_col: None
sim_col: "Ms (ampere/meter)_s"
exp_col: "Ms (ampere/meter)_e_all_augmented"
transform: 'log'
augment: True
modeltypes: "pysr_linear"
threshold: 50000.
transform: 'log'


artifact_paths:
  root: "artifacts/"
  images: "artifacts/images/"
  models: "artifacts/models/"