experiment: "log_sim2exp-re-free-augmented"
config_path: "configs/pytorch_mlp_augmented_re_free.yml"
material_group: "re_free"
data_path: "data/re_free_augmented_data.csv"

input_col: "Ms (ampere/meter)_s"
target_col: "Ms (ampere/meter)_e_re_free_augmented"

emb_col: None
threshold: 50000

transform: 'log'
# scaler: RobustScaler
augment: True
sim_col: "Ms (ampere/meter)_s"
exp_col: "Ms (ampere/meter)_e_re_free_augmented"

modeltypes: "pytorch"

artifact_paths:
  root: "artifacts/"
  images: "artifacts/images/"
  models: "artifacts/models/"