experiment: "mat200_logsim2exp"
config_path: "configs/pytorch_mlp_w_emb_config.yml"
material_group: None
data_path: "data/pairwise_df_no_Ms_leq_50000.csv"

input_col: "Ms (ampere/meter)_s"
target_col: "Ms (ampere/meter)_e"
augment: True
emb_col: 'mat200'
embedding_path: 'data/embeddings/element/matscholar200.json'

sim_col: "Ms (ampere/meter)_s"
exp_col: "Ms (ampere/meter)_e"

# scaler: RobustScaler
transform: 'log'
augment: False
modeltypes: "pytorch"
threshold: 50000.

artifact_paths:
  root: "artifacts/"
  images: "artifacts/images/"
  models: "artifacts/models/"
