experiment: "log_sim2exp_augmented-re"
config_path: "configs/scikit_models_config_augmented_re.yml"
material_group: "re"
artifact_path: "../artifacts/"

data_path: "data/re_augmented_data.csv"

input_col: "Ms (ampere/meter)_s"
target_col: "Ms (ampere/meter)_e_re_augmented"

augment: True
emb_col: None

sim_col: "Ms (ampere/meter)_s"
exp_col: "Ms (ampere/meter)_e_re_augmented"

# scaler: StandardScaler
transform: 'log'
modeltypes: "scikit"
threshold: 50000.

artifact_paths:
  root: "artifacts/"
  images: "artifacts/images/"
  data_plots: "artifacts/data_plots/"
  models: "artifacts/models/"

models:
  LinearRegression:
    model: LinearRegression
    parameters:
      fit_intercept: [true]
      positive: [true]

  Ridge:
    model: Ridge
    parameters:
      alpha: [0.001, 0.002, 0.003, 0.004]
      fit_intercept: [true]
      solver: ['auto']

  Lasso:
    model: Lasso
    init_args:
      max_iter: 10000
    parameters:
      alpha: [0.001, 0.002, 0.003, 0.004]
      fit_intercept: [true]
      selection: ['cyclic']

  RandomForest:
    model: RandomForestRegressor
    parameters:
      n_estimators: [300, 400, 500, 600]
      max_depth: [10]
      min_samples_split: [2]
      min_samples_leaf: [1, 2]
      random_state: [42]
